### ISSUE TITLE
download dataset

### ISSUE THREAD

**Issue by MiaoHu-Pro** [jinzhuoran/CogKGE#1]
Many thanks for providing this package.

When I run this code, the dataset is not to be downloaded.
These two ULR cannot be accessed now as follows:

#self.url = "http://49.232.8.218" #旧服务器
self.url = "http://43.154.73.63:9000/" #新服务器

Could you provide another URL for dataset download? or other methods to get the dataset.

Miao

**Comment by jinzhuoran** [comment]
Hi @MiaoHu-Pro, thanks for your attention. We'll provide a new URL soon.

**Comment by MiaoHu-Pro** [comment]
> Hi @MiaoHu-Pro, thanks for your attention. We'll provide a new URL soon.

@jinzhuoran  Thanks for your reply.  Please provide the new URL as soon as possible.

**Comment by jinzhuoran** [comment]
Dataset can be downloaded in [Baidu Pan](https://pan.baidu.com/s/1-aqsXvo5e2edQ-StQ0EYmw) (key: p986)

**Comment by MiaoHu-Pro** [comment]
Many thanks for providing the dataset.

**Comment by gsanou** [comment]
@MiaoHu-Pro Can you share the datasets please ? I cannot find it
Thank you 
Best
Gaoussou
